### ISSUE TITLE
Ide

### ISSUE THREAD

**Issue by ddkwork** [elliotchance/reflect#8]
Hello. Which ide your used?
Vscode?

**Comment by elliotchance** [comment]
At the moment I'm using [Sublime Text](https://www.sublimetext.com). However, I am biased because I created the [V plugin for Sublime](https://github.com/elliotchance/vlang-sublime).

**Comment by ddkwork** [comment]
> At the moment I'm using [Sublime Text](https://www.sublimetext.com). However, I am biased because I created the [V plugin for Sublime](https://github.com/elliotchance/vlang-sublime).

Thank you. How to debug v code?

**Comment by elliotchance** [comment]
You can also use the gcc debugger. Although, you should ask on the discord channel: https://discord.com/invite/vlang
